# Generated by Django 6.0.2 on 2026-03-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_simpleuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
