# Generated by Django 6.0.2 on 2026-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_simpleuser_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleUser',
            new_name='User',
        ),
    ]
